### ISSUE TITLE
Call to undefined function App\Http\Controllers\WebDav\fake()

### ISSUE THREAD

**Issue by hguenot** [m-thalmann/SecureDAV#2]
Hello,
I configured SecureDAV using the procedure https://m-thalmann.github.io/SecureDAV/installation/source.html
When I try to create a new user, I get this error.

In fact, this utility method comes from Laravel, but it requires fakerphp to be defined  (https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/helpers.php#L462) which is defined as a dev dependency in your composer.json.
In your guide, we don't install development dependencies.

BR.
Hervé

**Comment by m-thalmann** [comment]
Hello Hervé!
Thanks for reaching out, you are right, I totally overlooked this! Will fix this asap :)

As a workaround you can create the user with a label in the meantime

BR,
Matthias

**Comment by m-thalmann** [comment]
@hguenot hi again!
This was a very straightforward fix, I've already merged it. It will be part of the next release which I hope will be within the next week (still have an important bug to fix)

Thanks again for the bug report and have a great day!

**Comment by m-thalmann** [comment]
@hguenot just informing you that the new release was just created :)
